import Head from "next/head";
import React from "react";

import Header from "../../components/header/header";
import BodySection from "../../components/section/bodySection";
import Footer from "../../components/footer/footer";
import { fetchHeaderData } from "../../modules/common/service";
import { fetchCategoryPostAPI } from "../../modules/articles/service";
import { fetchMostReadPost, fetchFeaturedVideos } from "../../modules/widgets/service";

var hostname = "https://my-blog-seven-phi.vercel.app";
var href = "https://my-blog-seven-phi.vercel.app";

if (typeof window !== 'undefined') {
    hostname = window.location.origin;
    href = window.location.href
};

export const getStaticPaths = async () => {
    const categories = await fetch(process.env.STRAPI_URL + '/categories');
    const data = await categories.json();
    const categoriesSlug = [];

    data.map((category) => {
        if (category.slug != '' || category.slug != null) {
            categoriesSlug.push(category.slug);
        }
    })

    const paths = categoriesSlug.map((path) => {
        return {
            params: {
                category: path
            }
        }
    })

    return {
        paths,
        fallback: false
    }
}

export const getStaticProps = async (context) => {
    const { params } = context;
    const categoryData = await fetchCategoryPostAPI(params.category);
    const headerData = await fetchHeaderData();
    const mostReadPost = await fetchMostReadPost();
    const featuredVideo = await fetchFeaturedVideos();

    return {
        props: {
            category: categoryData.categories,
            headers: headerData.categories,
            popularArticles: mostReadPost.articles,
            featuredVideos: featuredVideo.featuredVideos
        },
    }
}

const Category = (props) => {
    const { category, headers, popularArticles, featuredVideos } = props;

    return <>
        <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header HeaderData={headers} />
        <BodySection categoryDetails={category} popularPost={popularArticles} featuredVideo={featuredVideos} />
        <Footer />
    </>
}
export default Category;