import Head from 'next/head';
import React from 'react';
import { gql } from '@apollo/client';

import client from "../apollo-client";
import Header from '../components/header/header';
import HomeBodySection from '../components/section/homeBodySection';
import styles from '../styles/Home.module.css';
import Footer from '../components/footer/footer';

const homeData = gql`
query {
  categories {
    id
    name
    slug
    articles {
      id
      title
      slug
      description
      category{
        name
      }
      author {
        id
        name
        picture{
          url
        }
      }
      image{
        url
      }
      createdAt
    }
  }
}`;

const headerData = gql`
query{
  categories{
    id
    name
    slug
  }
}`;

var hostname = "https://my-blog-seven-phi.vercel.app";
var href = "https://my-blog-seven-phi.vercel.app";

if (typeof window !== 'undefined') {
  hostname = window.location.origin;
  href = window.location.href
};

const fetchCategoriesData = async () => {
  const { data } = await client.mutate({
    mutation: homeData
  })
  return data;
}

const fetchHeaderData = async () => {
  const { data } = await client.mutate({
    mutation: headerData
  })
  return data;
}

export const getStaticProps = async (context) => {
  const categoriesData = await fetchCategoriesData();
  const headerData = await fetchHeaderData();

  return {
    props: {
      categories: categoriesData.categories,
      headers: headerData.categories
    }
  }
}

export default function Home(props) {
  const { categories, headers } = props;

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header HeaderData={headers} />
      <HomeBodySection Categories={categories} />
      <Footer />
    </>
  )
}
